# ベースイメージ
FROM node:20.6.0 AS builder

# 作業ディレクトリを設定
WORKDIR /app

# package.jsonとyarn.lockをコピー
COPY package*.json ./

# 依存関係をインストール
RUN npm install

# アプリケーションのソースコードをコピー
COPY . .

# アプリケーションをビルド
RUN npm run build

# アプリケーションを実行
CMD ["npm", "start"]

# 使用するポートを指定
EXPOSE 3000